version: '3'
services:
  gallery-dl-webui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8765:5000"
    volumes:
      - /home/cressil/dockers/webdl/testing:/media
      - /home/cressil/dockers/webdl/config:/app/data
    restart: unless-stopped
